app:
  images:
    path: D:\lego\images

spring:
  config:
    import:
      - "classpath:downloadPrices.yml"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/legodb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none