-- liquibase formatted sql
-- changeset EGlushkov:20260429-001-create-element-external-ids
-- preconditions onFail:MARK_RAN
-- preconditions: NOT TABLE_EXISTS(element_external_ids), TABLE_EXISTS(elements)

CREATE TABLE IF NOT EXISTS element_external_ids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    element_id BIGINT NOT NULL,
    element_external_id VARCHAR(20) NOT NULL,
    CONSTRAINT ext_ids_element_fk FOREIGN KEY (element_id) REFERENCES elements(id) ON DELETE CASCADE,
    CONSTRAINT element_external_id_uq UNIQUE (element_external_id)
    );
CREATE INDEX IF NOT EXISTS ext_ids_lookup_idx ON element_external_ids(element_external_id);

-- rollback DROP TABLE IF EXISTS element_external_ids CASCADE;