--liquibase tag:V1_init

CREATE TABLE IF NOT EXISTS themes (
                                      id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      name varchar(255) NULL,
    parent_id BIGINT,
    CONSTRAINT themes_pk PRIMARY KEY (id),
    CONSTRAINT themes_parent_id_fk FOREIGN KEY (parent_id) REFERENCES themes(id)
    );
CREATE INDEX IF NOT EXISTS themes_parent_id_idx ON themes USING btree (parent_id);

----
CREATE TABLE IF NOT EXISTS colors (
                                      id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      name varchar(255) NULL,
    rgb varchar(6) NULL,
    is_trans bool NULL,
    CONSTRAINT colors_pk PRIMARY KEY (id)
    );

----
CREATE TABLE IF NOT EXISTS part_categories (
                                               id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               name varchar(255) NULL,
    CONSTRAINT part_categories_pk PRIMARY KEY (id)
    );

----
CREATE TABLE IF NOT EXISTS parts (
                                     id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     part_num varchar(20) NOT NULL,
    name varchar(255) NULL,
    part_cat_id BIGINT NULL,
    part_material varchar(255) NULL,
    part_num_bricklink varchar(20) NULL,
    category_name_bricklink varchar(255) NULL,
    name_bricklink varchar(255) NULL,
    weight_grams numeric(7, 2) NULL,
    dimensions varchar(50) NULL,
    CONSTRAINT parts_pk PRIMARY KEY (id),
    CONSTRAINT parts_part_cat_id_fk FOREIGN KEY (part_cat_id) REFERENCES part_categories(id),
    CONSTRAINT part_num_uc UNIQUE (part_num)
    );
CREATE INDEX IF NOT EXISTS parts_part_num_idx ON parts USING btree (part_num);
CREATE INDEX IF NOT EXISTS parts_part_cat_id_idx ON parts USING btree (part_cat_id);
CREATE INDEX IF NOT EXISTS parts_part_num_blk_idx ON parts USING btree (part_num_bricklink);

----
CREATE TABLE IF NOT EXISTS part_relationships (
                                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                  rel_type varchar(1) NULL,
    child_part_id BIGINT NULL,
    parent_part_id BIGINT NULL,
    CONSTRAINT part_relationships_pk PRIMARY KEY (id),
    CONSTRAINT part_rel_child_fk FOREIGN KEY (child_part_id) REFERENCES parts(id),
    CONSTRAINT part_rel_parent_fk FOREIGN KEY (parent_part_id) REFERENCES parts(id),
    CONSTRAINT rel_type_child_part_id_parent_part_id_uc UNIQUE (rel_type, child_part_id, parent_part_id)
    );
CREATE INDEX IF NOT EXISTS part_relationships_child_part_id_idx ON part_relationships USING btree (child_part_id);
CREATE INDEX IF NOT EXISTS part_relationships_parent_part_id_idx ON part_relationships USING btree (parent_part_id);

----
CREATE TABLE IF NOT EXISTS elements (
                                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        element_id varchar(10) NOT NULL,
    part_id BIGINT NOT NULL,
    color_id BIGINT NULL,
    CONSTRAINT elements_pk PRIMARY KEY (id),
    CONSTRAINT elements_part_fk FOREIGN KEY (part_id) REFERENCES parts(id),
    CONSTRAINT elements_color_fk FOREIGN KEY (color_id) REFERENCES colors(id),
    CONSTRAINT element_id_uc UNIQUE (element_id)
    );
CREATE INDEX IF NOT EXISTS elements_part_id_idx ON elements USING btree (part_id);

----
CREATE TABLE IF NOT EXISTS alternate_part_number (
                                                     id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                     part_id BIGINT NOT NULL,
                                                     alt_part_num varchar(20) NOT NULL,
    CONSTRAINT alternate_part_number_pk PRIMARY KEY (id),
    CONSTRAINT alt_part_fk FOREIGN KEY (part_id) REFERENCES parts(id)
    );
CREATE INDEX IF NOT EXISTS alternate_part_number_part_id_idx ON alternate_part_number USING btree (part_id);

----
CREATE TABLE IF NOT EXISTS minifigs (
                                        id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        fig_num varchar(20) NOT NULL,
    name varchar(256) NULL,
    num_parts int4 NULL,
    img_url varchar(400) NULL,
    outer_img_url varchar(400) NULL,
    img_path varchar(400) NULL,
    CONSTRAINT minifigs_pk PRIMARY KEY (id),
    CONSTRAINT fig_num_uc UNIQUE (fig_num)
    );
CREATE INDEX IF NOT EXISTS minifigs_fig_num_idx ON minifigs USING btree (fig_num);

----
CREATE TABLE IF NOT EXISTS sets (
                                    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    set_num varchar(20) NOT NULL,
    name varchar(256) NULL,
    year int4 NULL,
    theme_id BIGINT NULL,
    name_bricklink varchar NULL,
    weight_grams numeric(7, 2) NULL,
    dimensions varchar(50) NULL,
    num_parts int4 NULL,
    img_url varchar(400) NULL,
    outer_img_url varchar(400) NULL,
    img_path varchar(400) NULL,
    CONSTRAINT sets_pk PRIMARY KEY (id),
    CONSTRAINT set_num_uc UNIQUE (set_num),
    CONSTRAINT sets_theme_fk FOREIGN KEY (theme_id) REFERENCES themes(id)
    );
CREATE INDEX IF NOT EXISTS sets_set_num_idx ON sets USING btree (set_num);
CREATE INDEX IF NOT EXISTS sets_year_idx ON sets USING btree (year);
CREATE INDEX IF NOT EXISTS sets_theme_id_idx ON sets USING btree (theme_id);

----
CREATE TABLE IF NOT EXISTS inventories (
                                           id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                           version int4 NULL,
                                           set_num varchar(20) NULL,
    CONSTRAINT inventories_pk PRIMARY KEY (id)
    );
CREATE INDEX IF NOT EXISTS inventories_set_num_idx ON inventories USING btree (set_num);

----
CREATE TABLE IF NOT EXISTS inventory_parts (
                                               id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               inventory_id BIGINT NULL,
                                               part_id BIGINT NULL,
                                               color_id BIGINT NULL,
                                               quantity int4 NULL,
                                               is_spare bool NULL,
                                               img_url varchar(400) NULL,
    outer_img_url varchar(400) NULL,
    img_path varchar(400) NULL,
    CONSTRAINT inventory_parts_pk PRIMARY KEY (id),
    CONSTRAINT inv_parts_inv_fk FOREIGN KEY (inventory_id) REFERENCES inventories(id),
    CONSTRAINT inv_parts_part_fk FOREIGN KEY (part_id) REFERENCES parts(id),
    CONSTRAINT inv_parts_color_fk FOREIGN KEY (color_id) REFERENCES colors(id),
    CONSTRAINT inventory_id_part_id_color_id_is_spare_uc UNIQUE (inventory_id, part_id, color_id, is_spare)
    );
CREATE INDEX IF NOT EXISTS inventory_parts_inventory_id_idx ON inventory_parts USING btree (inventory_id);
CREATE INDEX IF NOT EXISTS inventory_parts_part_id_idx ON inventory_parts USING btree (part_id);
CREATE INDEX IF NOT EXISTS inventory_parts_color_id_idx ON inventory_parts USING btree (color_id);

----
CREATE TABLE IF NOT EXISTS inventory_minifigs (
                                                  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                  inventory_id BIGINT NULL,
                                                  minifig_id BIGINT NULL,
                                                  quantity int4 NULL,
                                                  CONSTRAINT inventory_minifigs_pk PRIMARY KEY (id),
    CONSTRAINT inv_mf_inv_fk FOREIGN KEY (inventory_id) REFERENCES inventories(id),
    CONSTRAINT inv_mf_mf_fk FOREIGN KEY (minifig_id) REFERENCES minifigs(id),
    CONSTRAINT inventory_id_minifig_id_uc UNIQUE (inventory_id, minifig_id)
    );
CREATE INDEX IF NOT EXISTS inventory_minifigs_inventory_id_idx ON inventory_minifigs USING btree (inventory_id);
CREATE INDEX IF NOT EXISTS inventory_minifigs_minifig_id_idx ON inventory_minifigs USING btree (minifig_id);

----
CREATE TABLE IF NOT EXISTS inventory_sets (
                                              id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              inventory_id BIGINT NULL,
                                              set_id BIGINT NULL,
                                              quantity int4 NULL,
                                              CONSTRAINT inventory_sets_pk PRIMARY KEY (id),
    CONSTRAINT inv_sets_inv_fk FOREIGN KEY (inventory_id) REFERENCES inventories(id),
    CONSTRAINT inv_sets_set_fk FOREIGN KEY (set_id) REFERENCES sets(id),
    CONSTRAINT inventory_id_set_id_uc UNIQUE (inventory_id, set_id)
    );
CREATE INDEX IF NOT EXISTS inventory_sets_inventory_id_idx ON inventory_sets USING btree (inventory_id);
CREATE INDEX IF NOT EXISTS inventory_sets_set_id_idx ON inventory_sets USING btree (set_id);

--
CREATE TABLE IF NOT EXISTS element_info (
                                            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                            element_id BIGINT NOT NULL,
                                            state varchar(20) NOT NULL,
    count int8 NULL,
    price NUMERIC(10, 2) NULL,
    price_kuboka NUMERIC(10, 2) NULL,
    created TIMESTAMP NULL DEFAULT NOW(),
    updated TIMESTAMP NULL,
    count_updated TIMESTAMP NULL,
    price_updated TIMESTAMP NULL,
    price_kuboka_updated TIMESTAMP NULL,
    CONSTRAINT element_info_pk PRIMARY KEY (id),
    CONSTRAINT element_info_element_fk FOREIGN KEY (element_id) REFERENCES elements(id),
    CONSTRAINT element_id_state_uc UNIQUE (element_id, state)
    );
CREATE INDEX IF NOT EXISTS element_info_element_id_idx ON element_info USING btree (element_id);